-- Run this key in your Supabase SQL Editor to set up the table

create table orders (
  id bigint generated by default as identity primary key,
  name text,
  tag text,
  status text,
  entered_at bigint,
  ordered_at bigint,
  paid_at bigint,
  delivered_at bigint,
  location text,
  comments text
);

-- Enable Row Level Security (optional but recommended)
alter table orders enable row level security;

-- Policy to allow anonymous read/write (since we are using anon key for this demo, usually you'd want auth)
create policy "Enable access for all users" on orders for all using (true) with check (true);
